on:
  push:
    branches:
      - main

name: IntegrationTest
jobs:
  integrationTest:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-region: us-west-2
          # The Amazon Resource Name (ARN) of the role to assume. Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than with the provided credentials.
          role-to-assume: arn:aws:iam::265693559009:role/GlambdaIntegrationTestRole  
          audience: sts.amazonaws.com
          mask-aws-account-id: true
          role-duration-seconds: 300
          role-session-name: mrJoshCraneGlambda
      
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Test workflow"
        uses: actions/setup-go@v5

      - name: "Install glambda and run through usecases"
        run: |
          go install github.com/mr-joshcrane/glambda/cmd/glambda@latest
          glambda package testdata/correct_test_handler/main.go
          glambda deploy integration testdata/correct_test_handler/main.go
          glambda delete integration
      
